/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: '#FFF7F0',
        mint: '#BCF4DE',
        taupe: '#DED6D1',
        ink: '#190922',
        blush: '#EEC6CA',
        pink: '#FFB7C3',
        sage: '#CDE5D7',
        primary: '#336857',
        secondary: '#75565a',
        tertiary: '#6e5c3b',
        surface: '#fff8f4',
        background: '#fff8f4',
        'surface-bright': '#fff8f4',
        'surface-dim': '#e1d8d3',
        'surface-variant': '#e9e1dc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2ed',
        'surface-container': '#f5ece7',
        'surface-container-high': '#efe7e1',
        'surface-container-highest': '#e9e1dc',
        outline: '#707974',
        'outline-variant': '#c0c9c3',
        'on-surface': '#1e1b18',
        'on-surface-variant': '#404945',
        'on-background': '#1e1b18',
        'on-primary': '#ffffff',
        'on-primary-container': '#3d7160',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#7a5b5e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      spacing: {
        unit: '8px',
        'margin-safe': '5vw',
        'hero-offset': '120px',
        gutter: '24px',
      },
      fontFamily: {
        'body-lg': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-xl': ['Noto Serif', 'serif'],
        'label-caps': ['Noto Serif', 'serif'],
        'body-md': ['Noto Serif', 'serif'],
        'headline-xl-mobile': ['Noto Serif', 'serif'],
        'headline-md': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
